### ISSUE TITLE
Error parsing header X-XSS-Protection: 1; mode=block, 1; mode=block: expected semicolon at character position 14. The default protections will be applied.

### ISSUE THREAD

**Issue by joshuaadickerson** [mageinferno/docker-magento2-nginx#12]
See https://github.com/magento/magento2/issues/8734 for more info

Line 19 should be removed (because Magento doesn't seem to be fixing it)
https://github.com/mageinferno/docker-magento2-nginx/blob/master/conf/default.conf#L19

**Comment by markshust** [comment]
thank you. imho magento should NOT be adding these to code, as this should be a runtime-config option. regardless, i'll remove :)
